config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :channels do
    resource :channel_user
    resources :messages
  end

  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'channels#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :channel_users, dependent: :destroy
  has_many :users, through: :channel_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channel_user = current_user.channel_users.find_by(channel: @channel)
    @last_read_at = @channel_user&.last_read_at || @channel.created_at
    @channel_user&.touch(:last_read_at)
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: 'Channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def channel_params
      params.require(:channel).permit(:name)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
  def active_channel?(channel)
    channel == @channel
  end
end

app/views/channels/_form.html.erb
<%= form_with(model: channel, local: true) do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if channel.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', channel, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if channel.persisted? %>
      <%= link_to "Cancel", channel, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", channels_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Edit Channel</h1>

<%= render 'form', channel: @channel %>

app/views/channels/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Channels</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_channel_path, class: 'btn btn-primary' do %>
    Add New Channel
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    
        <th>Name</th>
    

            
      </tr>
    </thead>

    <tbody>
      <% @channels.each do |channel| %>
        <%= content_tag :tr, id: dom_id(channel), class: dom_class(channel) do %>
          
            <td><%= link_to channel.name, channel %></td>
          

          
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form', channel: @channel %>

app/views/channels/show.html.erb
<div class="row" data-controller="channel" data-channel-id="<%= @channel.id %>">
  <div class="col-sm-2">
    <%= render "shared/sidebar" %>
  </div>

  <div class="col-sm-10 relative">
    <div class="d-flex justify-content-between sticky-top bg-white border-bottom pt-2">
      <strong>#<%= @channel.name %></strong>

      <div>
        <%= link_to "Leave", channel_channel_user_path(@channel), method: :delete, class: "btn btn-link" %>
      </div>
    </div>

    <div data-target="channel.messages">
      <%= render @channel.messages %>
    </div>

  </div>

  <div class="fixed-bottom row">
    <div class="col-sm-10 offset-sm-2 p-2 bg-white">
      <% if current_user.channels.include?(@channel) %>
        <%= form_with model: [@channel, Message.new], data: { action: "ajax:success->channel#clearMessage" } do |form| %>
          <%= form.text_field :body, placeholder: "Message ##{@channel.name}", class: "form-control", data: { target: "channel.newMessage" } %>
        <% end %>

      <% else %>
        <%= link_to "Join #{@channel.name}", channel_channel_user_path(@channel), method: :post %>
      <% end %>
    </div>
  </div>
</div>